name: Auto start workflow process

on:
  push:
    branches:
      - main

jobs:
  printer_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: first name
        run: echo "CI"
      
      - name: last name
        run: echo "CD"